set-option -g base-index 1 
set-option -g pane-base-index 1
bind c new-window -c  "#{pane_current_path}"
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"
set-option -g mouse on
set -g status-bg cyan
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"
set-option -g mode-keys vi
